# Copyright 2023 Cerebras Systems.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# BERT-Large, MSL:128

train_input:
    data_processor: "BertCSVDynamicMaskDataProcessor"
    data_dir: "/software/cerebras/dataset/transformers/pyt_bert_csv/train_512k_uncased_msl128"
    vocab_file: "/home/$(whoami)/R_2.1.1/modelzoo/modelzoo/transformers/vocab/google_research_uncased_L-12_H-768_A-12.txt"
    max_sequence_length: 128
    max_predictions_per_seq: 20
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 1024
    whole_word_masking: False
    do_lower: True
    masked_lm_prob: 0.15
    shuffle: True
    shuffle_seed: 1
    num_workers: 8
    prefetch_factor: 10
    persistent_workers: True

eval_input:
    data_processor: "BertCSVDynamicMaskDataProcessor"
    data_dir: "/software/cerebras/dataset/transformers/pyt_bert_csv/train_512k_uncased_msl128"
    vocab_file: "/software/cerebras/acceptance_tests_2022/dataset/bert_lrg_new/google_research_uncased_L-12_H-768_A-12.txt"
    max_sequence_length: 128
    max_predictions_per_seq: 20
    # The effective batch size, which is evenly divided across "num_csx" systems used for the run
    batch_size: 256 # for GPU(16GB) set batch_size: 16
    whole_word_masking: False
    do_lower: True
    masked_lm_prob: 0.15
    shuffle: False
    shuffle_seed: 1 # also for deterministic masking
    num_workers: 2
    prefetch_factor: 10
    persistent_workers: True

model:
    vocab_size: 30522
    hidden_size: 1024
    num_hidden_layers: 24
    num_heads: 16
    filter_size: 4096
    encoder_nonlinearity: "gelu" # {"gelu", "relu", "silu", "gelu_new"}
    pooler_nonlinearity: "tanh"
    dropout_rate: 0.1
    attention_dropout_rate: 0.1
    max_position_embeddings: 512
    layer_norm_epsilon: 1.0e-5
    mlm_loss_weight: 0.058
    mixed_precision: True
    fp16_type: "cbfloat16"

optimizer:
    optimizer_type: "AdamW"
    weight_decay: 0.01
    learning_rate:
       - scheduler: "Linear"
         initial_learning_rate: 0.0
         end_learning_rate: 0.00019059938352471135 # (sqrt(3720.0/256.0)/2)*0.0001
         total_iters: 3200
       - scheduler: "Linear"
         initial_learning_rate: 0.00019059938352471135 # (sqrt(3720.0/256.0)/2)*0.0001
         end_learning_rate: 0.0
         total_iters: 77600
    loss_scaling_factor: "dynamic"
    max_gradient_norm: 1.0

runconfig:
    max_steps: 1000
    log_steps: 100
    checkpoint_steps: 1000
    seed: 1
    model_dir: "./model_dir"
    save_initial_checkpoint: True
    eval_steps: 220
    use_cs_grad_accum: True
